name: Placo building

on:
  push:
  workflow_dispatch:

jobs:
  test-placo:
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Configuring Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Showing Python & pip version
        run: |
          python --version
          pip --version

      - name: Upodating pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Cloning PlaCo repository
        run: |
          git clone --depth=1 https://github.com/rhoban/placo.git

      - name: Installing requirements
        run: |
          cd placo/
          bash scripts/requirements.sh

      - name: Showing ~/.bashrc
        run: |
          cat ~/.bashrc
          source ~/.bashrc
          echo $LD_LIBRARY_PATH
          echo $CMAKE_PREFIX_PATH

      - name: CMake
        run: |
          source ~/.bashrc
          cd placo/
          mkdir build
          cmake -S . -B build

      - name: Building PlaCo
        run: |
          cd placo/build
          make -j4
          
