name: Placo building

on:
  push:
  workflow_dispatch:

jobs:
  test-placo:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Configuring Python
        uses: actions/setup-python@v5

      - name: Showing Python & pip version
        run: |
          python --version
          pip --version

      - name: Upodating pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Cloning PlaCo repository
        run: |
          git clone --depth=1 https://github.com/rhoban/placo.git

      - name: Installing requirements
        run: |
          cd placo/
          bash scripts/requirements.sh

      # This step can be done by the user with "source ~/.bashrc" after running the requirements
      - name: Adding environment variables to GITHUB_ENV
        run: |
          echo "PATH=/opt/openrobots/bin:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo PYTHON_VERSION=`python --version|cut -d" " -f2|cut -d"." -f-2` >> $GITHUB_ENV
          echo "PYTHONPATH=/opt/openrobots/lib/python${PYTHON_VERSION}/site-packages:$PYTHONPATH" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: CMake
        run: |
          cd placo/
          mkdir build
          cmake -S . -B build

      - name: Building PlaCo
        run: |
          cd placo/build
          make -j$(nproc)

      - name: Running tests
        run: |
          echo "PYTHONPATH=$PWD/build/lib/python-${PYTHON_VERSION}/site-packages/:$PYTHONPATH" >> $GITHUB_ENV
          python -m unittest discover python/tests/ "*_test.py"



          
