name: Doxygen

on:
  push:
  workflow_dispatch:

env:
  CIBW_SKIP: "*i686 *musl* *armv7* *ppc64* *s390*"
  CIBW_REPAIR_WHEEL_COMMAND: ""
  CIBW_TEST_REQUIRES: matplotlib
  CIBW_TEST_COMMAND: "python -m unittest discover python/tests/ \"*_test.py\""

jobs:
  build_wheels:
    name: Wheel ${{ matrix.os }}, ${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pyver: [cp312]

    steps:
      - name: Cloning PlaCo repository
        run: git clone --depth=1 https://github.com/rhoban/placo.git

      - name: Installing Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Running doxygen
        run: |
          cd placo/
          doxygen Doxyfile

      - uses: actions/upload-artifact@v4
        with:
          name: doxygen
          path: ./placo/xml/*
