name: Test placo sur Linux

on:
  push:
  workflow_dispatch:

jobs:
  test-placo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 3.11+ recommandé sur macos-latest pour éviter des soucis de compatibilité[5]

      - name: Showing py version
        run: |
          python --version
          pip --version

      - name: Mise à jour de pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Installation de placo
        run: |
          echo "DEBUG: Installation de placo"
          pip install placo

      - name: clone
        run: |
          git clone https://github.com/rhoban/placo.git
          
      - name: Test
        run: |
          cd placo/python
          python -m unittest discover tests/ "*_test.py"
          
          

