name: pip install and test PlaCo

on:
  push:
  workflow_dispatch:

jobs:
  test-placo:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest, ubuntu-latest, macos-13, ubuntu-24.04-arm]
        exclude:
          - python-version: "3.8"
            os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configuring Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Showing Python & pip version
        run: |
          python --version
          pip --version

      - name: Upodating pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Installing PlaCO
        run: |
          pip install placo matplotlib

      - name: Cloning PlaCo repository
        run: |
          git clone --depth=1 https://github.com/rhoban/placo.git

      - name: Running PlaCo tests
        run: |
          cd placo/python
          python -m unittest discover tests/ "*_test.py"
